dist: xenial
sudo: false
cache:
  directories:
  - buildout/eggs
matrix:
  fast_finish: true
before_install:
  - sudo apt-get install -y python3-venv
install:
- bin/bootstrap
- bin/build annotate
- bin/build
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage
- pip install coveralls
- coveralls
