version: 2
jobs:
        build:
                docker:
                        - image: python:3.7
        steps:
                - checkout
                - run: bin/bootstrap
                - run: bin/build annotate
                - run: bin/build
                - run: bin/code-analysis
                - run: bin/test
