version: 2
jobs:
        build:
                docker:
                        - image: python:3.7
        steps:
                - bin/bootstrap
                - bin/build annotate
                - bin/build
                - bin/code-analysis
                - bin/test
